name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v4
        
        - name: login to docker hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Build and Push docker image
          run:  |
              docker image build . -t sourabhtailor/nodeimage:latest
              docker push sourabhtailor/nodeimage:latest
   deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Deploy to remote server via SSH
          uses: appleboy/ssh-action@v1.0.0
          env:
             DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
             DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
             APP_USERNAME: ${{ secrets.APP_USERNAME }}
             APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
             APP_SECRET_MESSAGE: ${{ secrets.APP_SECRET_MESSAGE }}
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: 22
            envs: DOCKER_USERNAME, DOCKER_PASSWORD, APP_USERNAME, APP_PASSWORD, APP_SECRET_MESSAGE

            script_stop: true
            script: |
              if [ -z "$DOCKER_USERNAME" ]; then echo "🚫 DOCKER_USERNAME is missing"; fi
              if [ -z "$DOCKER_PASSWORD" ]; then echo "🚫 DOCKER_PASSWORD is missing"; fi
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker pull sourabhtailor/nodeimage:latest
              docker stop nodeapp || true
              docker rm nodeapp || true
              docker run -d --name nodeapp -p 80:3000 \
                -e USERNAME="$APP_USERNAME" \
                -e PASSWORD="$APP_PASSWORD" \
                -e SECRET_MESSAGE="$APP_SECRET_MESSAGE" \
                sourabhtailor/nodeimage:latest
 
