name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: set_tag
        run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push
        run: |
          docker build . -t sourabhtailor/nodeimage:${{ steps.set_tag.outputs.tag }}
          docker push sourabhtailor/nodeimage:${{ steps.set_tag.outputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker pull sourabhtailor/nodeimage:${{ needs.build.outputs.image_tag }}
            docker stop nodeapp || true
            docker rm nodeapp || true
            docker run -d --name nodeapp -p 80:3000 \
              -e USERNAME="$APP_USERNAME" \
              -e PASSWORD="$APP_PASSWORD" \
              -e SECRET_MESSAGE="$APP_SECRET_MESSAGE" \
              sourabhtailor/nodeimage:${{ needs.build.outputs.image_tag }}
        envs: DOCKER_USERNAME,DOCKER_PASSWORD,APP_USERNAME,APP_PASSWORD,APP_SECRET_MESSAGE
