name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v4
        
        - name: login to docker hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Build and Push docker image
          run:  |
              docker image build . -t sourabhtailor/nodeimage:latest
              docker push sourabhtailor/nodeimage:latest
   deploy:
     runs-on: ubuntu-latest
     
     steps:
       - name: deploy to remote server via ssh
         uses: appleboy/ssh-action@v1.0.0
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           password: ${{ secrets.SERVER_PASSWORD }}
           port: 22
           envs: DOCKER_USERNAME,DOCKER_PASSWORD,APP_USERNAME,APP_PASSWORD,APP_SECRET_MESSAGE
           script: 
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                docker pull sourabhtailor/nodeimage:latest
                docker stop nodeapp || true
                docker rm nodeapp  || ture
                docker run -d --name nodeapp -p 80:3000 -e USERNAME="$APP_USERNAME" -e PASSWORD="$APP_PASSWORD" -e PASSWORD="$APP_PASSWORD" sourabhtailor/nodeimage:latest
              
