name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nodeimage:$(date +%s)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push the Docker image
      run: |
         IMAGE_TAG=nodeimage:$(date +%s)
         docker build . --file Dockerfile --tag sourabhtailor/$IMAGE_TAG
         docker push sourabhtailor/$IMAGE_TAG
  
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to remote server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{secrets.SERVER_PASSWORD}}
        port: 22
        script: |
          docker pull sourbhtailor/nodeimage:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name nodeapp -p 80:3000 sourabhtailor/nodeimage:latest
